name: Generate requirements.txt

on:
  push:
    branches:
      - main  # adjust if your default branch is different

jobs:
  generate-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # adjust to your Python version
        
      - name: Install pipreqs
        run: |
          python -m pip install --upgrade pip
          pip install pipreqs
      
      - name: Generate requirements.txt
        run: |
          pipreqs .
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Generate requirements.txt" || exit 0  # exit 0 to allow commit even if there are no changes
          git push
