name: Generate Requirements

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_requirements:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools
        pip install -r requirements.txt
    
    - name: Generate Requirements
      run: |
        python generate_requirements.py > requirements.txt
    
    - name: Commit and Push
      run: |
        git config --global user.email "paul@schickler.org"
        git config --global user.name "paulsch1"
        git add requirements.txt
        git commit -m "requirements.txt"
        git push https://paulsch1:${{ secrets.PAT }}@github.com/paulsch1/capstone
      env:
        PAT: ${{ secrets.PAT }}
